package com.prasannjeet.klokka.mail;

import io.quarkus.qute.TemplateData;
import java.util.List;

// Everything templates/digest.html shows, already translated and formatted (CHQ-148). The template is generated by
// scripts/emails/build.mjs from the same layout as the Logto emails; it only places these values.
@TemplateData
public record DigestMail(String lang, String subject, String title1, String title2, String greeting, String intro,
        List<Workspace> workspaces, String action, String webUrl, String unsubscribe, String footer, String site,
        String siteHost) {

    @TemplateData
    public record Workspace(String emoji, String name, String range, List<Day> days, String hoursLabel, String hours,
            String monthLabel, String monthHours) {}

    // One cell of the week grid: `hot` is the week's busiest day, `off` a day without hours.
    @TemplateData
    public record Day(String label, String value, boolean hot, boolean off) {}
}
