// Generates src/i18n/catalogue.generated.ts from i18n/sv.json and i18n/en.json (docs/DECISIONS.md D2).
// The JSON files are the source of truth (the API reads the same files for push and email text); the
// generated module gives TypeScript a flat, `as const` catalogue plus the MessageKey and MessageParams
// types so a wrong key, a missing translation or a missing placeholder fails `tsc` in web and mobile.
// `--check` regenerates into memory and fails when the committed file differs.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

type Tree = { [key: string]: string | Tree };
type Flat = Record<string, string>;

const ROOT = new URL('../', import.meta.url);
const OUT = fileURLToPath(new URL('src/i18n/catalogue.generated.ts', ROOT));
const PLACEHOLDER = /\{([a-zA-Z][a-zA-Z0-9]*)\}/g;
const PLURAL = /^(.*)_(one|other)$/;
const EM_DASH = String.fromCharCode(0x2014);

function flatten(tree: Tree, prefix = '', acc: Flat = {}): Flat {
  for (const [k, v] of Object.entries(tree)) {
    const key = prefix ? `${prefix}.${k}` : k;
    if (typeof v === 'string') acc[key] = v;
    else flatten(v, key, acc);
  }
  return acc;
}

function load(locale: string): Flat {
  const file = fileURLToPath(new URL(`i18n/${locale}.json`, ROOT));
  return flatten(JSON.parse(readFileSync(file, 'utf8')) as Tree);
}

function placeholders(value: string): string[] {
  return [...new Set([...value.matchAll(PLACEHOLDER)].map((m) => m[1] as string))].sort();
}

function fail(message: string): never {
  console.error(`gen-i18n: ${message}`);
  process.exit(1);
}

const sv = load('sv');
const en = load('en');

// Structural checks before anything is generated: same keys, same placeholders, both plural forms, no em dash.
const svKeys = Object.keys(sv).sort();
const enKeys = Object.keys(en).sort();
const missingInEn = svKeys.filter((k) => !(k in en));
const extraInEn = enKeys.filter((k) => !(k in sv));
if (missingInEn.length || extraInEn.length) {
  fail(`key mismatch. Missing in en: [${missingInEn.join(', ')}]. Extra in en: [${extraInEn.join(', ')}]`);
}
for (const key of svKeys) {
  const a = placeholders(sv[key] as string);
  const b = placeholders(en[key] as string);
  if (a.join() !== b.join())
    fail(`placeholder mismatch on ${key}: sv {${a.join(',')}} vs en {${b.join(',')}}`);
  for (const [locale, value] of [
    ['sv', sv[key]],
    ['en', en[key]],
  ] as const) {
    if ((value as string).includes(EM_DASH)) fail(`em dash in ${locale} value of ${key}`);
  }
  const m = PLURAL.exec(key);
  if (m) {
    const other = `${m[1]}_${m[2] === 'one' ? 'other' : 'one'}`;
    if (!(other in sv)) fail(`plural key ${key} has no ${other} counterpart`);
    if (`${m[1]}` in sv) fail(`plural base ${m[1]} clashes with a plain key`);
  }
}

// Public keys: plain keys as they are; `x_one`/`x_other` collapse to `x` with a required `count` param.
const publicKeys = new Map<string, { plural: boolean; params: string[] }>();
for (const key of svKeys) {
  const m = PLURAL.exec(key);
  if (m) {
    const base = m[1] as string;
    const existing = publicKeys.get(base) ?? { plural: true, params: [] };
    existing.params = [...new Set([...existing.params, 'count', ...placeholders(sv[key] as string)])].sort();
    publicKeys.set(base, existing);
  } else {
    publicKeys.set(key, { plural: false, params: placeholders(sv[key] as string) });
  }
}

const q = (s: string) => JSON.stringify(s);
const catalogue = (flat: Flat) => svKeys.map((k) => `  ${q(k)}: ${q(flat[k] as string)},`).join('\n');
const paramsType = [...publicKeys.entries()]
  .map(([k, v]) =>
    v.params.length === 0
      ? `  ${q(k)}: Record<never, never>;`
      : `  ${q(k)}: { ${v.params.map((p) => `${p}: string | number`).join('; ')} };`,
  )
  .join('\n');
const pluralKeys = [...publicKeys.entries()]
  .filter(([, v]) => v.plural)
  .map(([k]) => `  ${q(k)},`)
  .join('\n');

const output = `// GENERATED by packages/core/scripts/gen-i18n.ts from i18n/sv.json and i18n/en.json. Do not edit.
// Regenerate with \`npm run generate -w @klokka/core\`; \`npm run check -w @klokka/core\` fails when stale.
/* eslint-disable */

export const sv = {
${catalogue(sv)}
} as const;

export const en = {
${catalogue(en)}
} as const satisfies Record<keyof typeof sv, string>;

export type CatalogueKey = keyof typeof sv;

export type MessageParams = {
${paramsType}
};

export type MessageKey = keyof MessageParams;

export const pluralKeys: ReadonlySet<string> = new Set<string>([
${pluralKeys}
]);
`;

if (process.argv.includes('--check')) {
  const current = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
  if (current !== output) {
    fail(
      'src/i18n/catalogue.generated.ts is out of date: run `npm run generate -w @klokka/core` and commit it.',
    );
  }
  console.log(`gen-i18n: catalogue is up to date (${svKeys.length} strings, ${publicKeys.size} keys)`);
} else {
  writeFileSync(OUT, output);
  console.log(`gen-i18n: wrote ${OUT} (${svKeys.length} strings, ${publicKeys.size} keys)`);
}
